steps:
  - label: ":python: test"
    command: ./scripts/test
    env:
      CONDA_ENV_NAME: "md_dataset_package"
    agents:
      python-r-4.3: true

  - label: ":lint-roller: lint"
    command: ./scripts/lint
    env:
      CONDA_ENV_NAME: "md_dataset_package"
    agents:
      python-r-4.3: true

  - wait: ~
    key: prep

  ################################################################################
  ## Image
  ################################################################################
  - block: ":warning: build and push docker images?"
    key: block_image
    depends_on: prep
    branches: "!main"

  - label: ":docker: dataset base image"
    key: build_base_image
    depends_on: ["block_image", "prep"]
    command: scripts/build-push
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      DOCKER_FILE: "base.Dockerfile"
      REPO_NAME: "md_dataset_package_base"
      GIT_HASH: "${BUILDKITE_COMMIT}"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_dataset_base/docker"

  - label: ":docker: dataset base r image"
    key: build_base_r_image
    depends_on: ["build_base_image"]
    command: scripts/build-push
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      DOCKER_FILE: "r.base.Dockerfile"
      REPO_NAME: "md_dataset_package_r_base"
      GIT_HASH: "${BUILDKITE_COMMIT}"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_dataset_r_base/docker"

  - label: ":docker: dataset python"
    key: build_python_image
    depends_on: ["build_base_image"]
    command: scripts/build-push
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      DOCKER_FILE: "py.Dockerfile"
      REPO_NAME: "md_dataset_package_py"
      GIT_HASH: "${BUILDKITE_COMMIT}"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_dataset_py/docker"

  - label: ":docker: dataset R"
    key: build_r_image
    depends_on: ["build_base_r_image"]
    command: scripts/build-push
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      DOCKER_FILE: "r.Dockerfile"
      REPO_NAME: "md_dataset_package_r"
      GIT_HASH: "${BUILDKITE_COMMIT}"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_dataset_r/docker"

  - label: ":github: tag"
    key: tag_package
    depends_on: ["build_python_image", "build_r_image"]
    command: scripts/tag
    env:
      AWS_REGION: "ap-southeast-2"
      AWS_DEFAULT_REGION: "ap-southeast-2"
      AWS_PROFILE: "eb-services-cli"
      BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
      GIT_HASH: "${BUILDKITE_COMMIT}"
    agents:
      ebdeploy: true
    concurrency: 1
    concurrency_group: "md_dataset/tag"
